sudo: required

language: go
go:
  - "1.10.x"

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2

install:
  - dep ensure

script:
  - make test-report
  - make lint

after_success:
  - go get github.com/mattn/goveralls; $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
